databases:
  - name: hospitaldb
    plan: free
    postgresMajorVersion: "17"

services:
  - type: web
    name: hospital-appointment-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: hospitaldb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hospitaldb
          property: port
      - key: DB_NAME
        fromDatabase:
          name: hospitaldb
          property: database
      - key: DB_USER
        fromDatabase:
          name: hospitaldb
          property: user
      - key: DB_PASS
        fromDatabase:
          name: hospitaldb
          property: password
